<a href="https://colab.research.google.com/github/harshalkumeriya/Deep-Learning-with-Pytoch/blob/master/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'1.5.1+cu101'

Tensors Basics

A tensor is an array: that is, a data structure that stores a collection of numbers that are accessible individually using an index, and that can be indexed with multiple indices.

Python lists or tuples of numbers are collections of Python objects that are individually allocated in memory. PyTorch tensors or NumPy arrays, on the other hand, are views over (typically) contiguous memory blocks containing unboxed C numeric types rather than Python objects. 

e.g. Each element is a 32-bit (4-byte) float in this case, which means storing a 1D tensor of 1,000,000 float numbers will require exactly 4,000,000 contiguous bytes, plus a small overhead for the metadata (such as dimensions and numeric type).

In [3]:
torch.empty(5,3)

tensor([[3.5272e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])

In [4]:
torch.rand(5,3)

tensor([[0.7279, 0.1093, 0.8053],
        [0.2931, 0.0660, 0.8741],
        [0.9902, 0.1855, 0.8386],
        [0.4110, 0.7720, 0.4862],
        [0.2538, 0.2761, 0.9723]])

In [5]:
torch.ones(5,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.zeros(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [44]:
torch.ones(3, dtype=torch.float16)

tensor([1., 1., 1.], dtype=torch.float16)

Tensors can reside in CPU or GPU

In [64]:
cpu_tensor = torch.randn(2)
cpu_tensor.device

device(type='cpu')

In [65]:
gpu_tensor = cpu_tensor.to('cuda')
gpu_tensor.device

device(type='cuda', index=0)

In [8]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

Tensor slicing

In [9]:
points[:3]

tensor([4., 1., 5.])

In [10]:
points[1:]

tensor([1., 5., 3., 2., 1.])

In [11]:
points = torch.empty(6)
points

tensor([3.5282e-35, 0.0000e+00, 7.0065e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00])

In [12]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

points

tensor([4., 1., 5., 3., 2., 1.])

In [13]:
z = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [14]:
z.size()

torch.Size([3, 2])

In [15]:
z.dtype

torch.float32

In [16]:
image_tensor = torch.randn(3,28,28) # shape (channels, rows, columns)

batch_tensor = torch.randn(2,3,28,28) # shape (batch, channels, rows, columns)

weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [17]:
# here -3 means channels dimension, counting from last.
img_gray_naive = image_tensor.mean(-3)
batch_gray_naive = batch_tensor.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([28, 28]), torch.Size([2, 28, 28]))

In [18]:
weights.shape

torch.Size([3])

In [19]:
x = weights.unsqueeze(-1)
print(x)
print(x.shape)

tensor([[0.2126],
        [0.7152],
        [0.0722]])
torch.Size([3, 1])


In [20]:
x.unsqueeze(-1).shape

torch.Size([3, 1, 1])

In [21]:
x.unsqueeze_(-1).shape

torch.Size([3, 1, 1])

In [22]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)

In [23]:
img_weights = (image_tensor * unsqueezed_weights)
batch_weights = (batch_tensor * unsqueezed_weights) # automatically append 1 leading dimension for multiplication (BROADCASTING)

In [24]:
unsqueezed_weights.shape, batch_tensor.shape, batch_weights.shape

(torch.Size([3, 1, 1]), torch.Size([2, 3, 28, 28]), torch.Size([2, 3, 28, 28]))

In [25]:
# giving name to tensor
weighted_names = torch.tensor([0.4765, 0.3456, 0.1234], names = ['channels'])
weighted_names

/pytorch/c10/core/TensorImpl.h:806: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable.


tensor([0.4765, 0.3456, 0.1234], names=('channels',))

In [26]:
# adding names to already existing tensor
img_named = image_tensor.refine_names(..., 'channels', 'rows', 'columns')
img_named.names, img_named.shape

(('channels', 'rows', 'columns'), torch.Size([3, 28, 28]))

In [27]:
weights_aligned = weighted_names.align_as(img_named)
weights_aligned.shape , weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [28]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([28, 28]), ('rows', 'columns'))

**Tensor Operation**

In [57]:
a = torch.ones(3,2)
a.shape

torch.Size([3, 2])

In [30]:
b = torch.randn(3,2)
b.shape

torch.Size([3, 2])

In [31]:
a_t = a.transpose(0,1)
a_t.shape

torch.Size([2, 3])

In [58]:
a.t()

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [66]:
torch.rand(10).max()

tensor(0.8907)

In [69]:
torch.randn(2,2).log1p()

tensor([[0.8655, 0.0257],
        [0.7440, 0.0082]])

In [70]:
torch.rand(2,2).log2()

tensor([[-0.1797, -2.1491],
        [-2.2154, -0.7768]])

In [32]:
a + b

tensor([[ 0.6324,  1.3278],
        [-0.9490,  0.3466],
        [ 0.7498,  0.1636]])

In [33]:
torch.add(a,b)

tensor([[ 0.6324,  1.3278],
        [-0.9490,  0.3466],
        [ 0.7498,  0.1636]])

In [34]:
# inplace 
a.add_(b)

tensor([[ 0.6324,  1.3278],
        [-0.9490,  0.3466],
        [ 0.7498,  0.1636]])

In [35]:
a

tensor([[ 0.6324,  1.3278],
        [-0.9490,  0.3466],
        [ 0.7498,  0.1636]])

In [36]:
temp_t = torch.randn(4,4)
temp_t.shape

torch.Size([4, 4])

In [37]:
temp_t.view(16)

tensor([ 1.4869,  1.9112, -0.6781,  1.6209,  0.9436, -0.1546, -0.5087, -0.8345,
        -0.8880, -0.3725,  0.1156,  1.5530,  0.0769, -1.0305, -0.3154,  0.8159])

In [38]:
temp_t.view(-1,8)

tensor([[ 1.4869,  1.9112, -0.6781,  1.6209,  0.9436, -0.1546, -0.5087, -0.8345],
        [-0.8880, -0.3725,  0.1156,  1.5530,  0.0769, -1.0305, -0.3154,  0.8159]])

In [71]:
temp_t.reshape(-1,8)

tensor([[ 1.4869,  1.9112, -0.6781,  1.6209,  0.9436, -0.1546, -0.5087, -0.8345],
        [-0.8880, -0.3725,  0.1156,  1.5530,  0.0769, -1.0305, -0.3154,  0.8159]])

Bridge between numpy and Pytorch

In [39]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [40]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [41]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [42]:
import numpy as np
a1 = np.ones(5)
b1 = torch.from_numpy(a1)
print(a1)
print(b1)
np.add(a1, 1, out=a1)
print(a1)
print(b1)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [43]:
torch.cuda.is_available()

True

**Requires Gradient**

In [59]:
x = torch.randn(2,2, requires_grad=True)
print(x)

tensor([[-0.4097, -0.9437],
        [ 1.0972,  0.2880]], requires_grad=True)


In [60]:
x.requires_grad

True

In [61]:
y = x + 2
y = (y ** 2 ) / 2
out = y.mean()

In [62]:
out.backward()

In [63]:
x.grad

tensor([[0.3976, 0.2641],
        [0.7743, 0.5720]])